info:
  namespace: arena
items:
  globe:
    display_name: "Globe des Navigations"
    permission: arena.globe
    resource:
      material: PAPER
      generate: false
      model_path: items/globe
    behaviours:
      furniture:
        entity: item_display
        solid: true
        fixed_rotation: true
        hitbox:
          length: 1
          height: 2
          width: 1
        placeable_on:
          walls: false
          ceiling: false
          floor: true
        display_transformation:
          translation:
            x: 0
            y: 0.5
            z: 0
          scale:
            x: 1
            y: 1
            z: 1
