info:
  namespace: omc_contest
items:
  borne:
    display_name: "Borne"
    permission: contest.borne
    resource:
      material: PAPER
      generate: false
      model_path: items/borne
    behaviours:
      furniture:
        entity: item_display
        solid: true
        fixed_rotation: true
        hitbox:
          length: 1
          height: 2
          width: 3
          width_offset: 0.5
        placeable_on:
          walls: false
          ceiling: false
          floor: true
        display_transformation:
          translation:
            x: 0
            y: 0.92
            z: 0
          scale:
            x: 1.5
            y: 1.5
            z: 1.5
