info:
  namespace: elitecreatures
categories:
  halloween_decoration_v1:
    enabled: true
    icon: "elitecreatures:halloween_decoration_v1_smile_flag"
    name: "Halloween Decoration v1"
    permission: "ia.menu.halloween_decoration_v1"
    items:
      - "elitecreatures:halloween_decoration_v1_broom"
      - "elitecreatures:halloween_decoration_v1_candle"
      - "elitecreatures:halloween_decoration_v1_celling_lamp"
      - "elitecreatures:halloween_decoration_v1_mr_thing"
      - "elitecreatures:halloween_decoration_v1_picture"
      - "elitecreatures:halloween_decoration_v1_pumpkin_1"
      - "elitecreatures:halloween_decoration_v1_pumpkin_2"
      - "elitecreatures:halloween_decoration_v1_pumpkin_3"
      - "elitecreatures:halloween_decoration_v1_pumpkin_4"
      - "elitecreatures:halloween_decoration_v1_rose_in_glass"
      - "elitecreatures:halloween_decoration_v1_scarecrow"
      - "elitecreatures:halloween_decoration_v1_skull_jar"
      - "elitecreatures:halloween_decoration_v1_skull_sun_flower"
      - "elitecreatures:halloween_decoration_v1_smile_flag"
      - "elitecreatures:halloween_decoration_v1_spider_in_jar"
      - "elitecreatures:halloween_decoration_v1_tomb_stone_1"
      - "elitecreatures:halloween_decoration_v1_tomb_stone_2"
      - "elitecreatures:halloween_decoration_v1_trick_or_treat_bowl"
      - "elitecreatures:halloween_decoration_v1_wall_lamp"
      - "elitecreatures:halloween_decoration_v1_witch_pot"
